[build]
  command = "echo 'No build step'"
  functions = "notebook_app_backend/functions"  # Correct path to your functions directory

[functions]
  directory = "notebook_app_backend/functions"  # Points to the correct functions directory


