[build]
    command = "echo 'No build step'"
    functions = "functions"  # Directory where your functions are now located

[functions]
    directory = "functions"  # Points to the functions directory

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/index.js"
    status = 200
